sharerich.settings:
  type: config_object
  label: Settings
  mapping:
    allowed_html:
      type: string
    facebook_app_id:
      type: string
    facebook_site_url:
      type: string
    youtube_username:
      type: string
    github_username:
      type: string
    instagram_username:
      type: string
    twitter_user:
      type: string
