sharerich.set.*:
  type: config_entity
  label: 'Sharerich set'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    services:
      type: sequence
      label: 'Enabled services'
      sequence:
        - type: sequence
          sequence:
            - type: string

block.settings.sharerich:
  type: block_settings
  label: 'Sharerich block'
  mapping:
    sharerich_set:
      type: string
      label: 'Sharerich set'
    orientation:
      type: string
      label: 'Orientation'
    sticky:
      type: boolean
      label: 'Stick to the top when scrolling'
